config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :vacancies, only: [:index, :new]
  end
  
  get 'users/:user_id/candidatures', to: 'candidatures#index', as: 'user_candidatures'
  
  resources :vacancies do
    resources :candidatures, only: [:index, :new]
    resources :comments, only: [:index, :new]
    
    collection do
      put :update_multiple
      get :autocomplete
    end
    
    member do
      put :recommend
      put :accept_recommendation
      put :deny_recommendation 
      put :close
      put :reopen
    end
  end
  
  resources :candidatures do
    resources :comments, only: [:index, :new]
    
    collection do
      put :update_multiple
      get :autocomplete
    end
    
    member do
      get :accept
      get :deny
      get :quit
    end
  end
  
  namespace 'workflow' do
    resources :vacancies, controller: 'vacancies', only: :index do
      collection do
        get '/' => 'vacancies#open', as: :open
        
        get :autocomplete
        
        get :open
        get :recommended
        get :denied
        get :closed
      end
    end
    
    resources :candidatures, controller: 'candidatures', only: :index do
      collection do
        get '/' => 'candidatures#new', as: :new
         
        get :autocomplete 
         
        get :new
        get :accepted
        get :denied
      end
    end
  end
end

app/models/state_machines/vacancy.rb
module StateMachines::Vacancy
  def self.included(base)
    base.extend ClassMethods
    
    base.class_eval do
      attr_accessor :current_user
      
      const_set 'STATES', [:open, :recommended, :denied, :closed]
      const_set 'EVENTS', [:accept_recommendation, :deny_recommendation, :close, :reopen]
      
      after_initialize :set_initial_state
      
      state_machine :state, initial: :new do
        event :recommend do
          transition :new => :recommended 
        end
        
        event :accept_recommendation do
          transition :recommended => :open  
        end
        
        event :deny_recommendation do
          transition :recommended => :denied  
        end
        
        event :do_open do
          transition :new => :open 
        end
        
        event :close do
          transition :open => :closed
        end
        
        event :reopen do
          transition [:denied, :closed] => :open
        end
      end
      
      private
      
      def set_initial_state
        self.state ||= :new
      end
    end
  end
  
  module ClassMethods
  end
end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  include StateMachines::Vacancy
  
  belongs_to :project
  belongs_to :offeror, class_name: 'User'
  belongs_to :author, class_name: 'User'
  belongs_to :resource, polymorphic: true
  belongs_to :project_user
  
  has_many :candidatures, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  
  accepts_nested_attributes_for :candidatures, allow_destroy: true, reject_if: ->(t) { t['name'].blank? }
  scope :open, -> { where(state: 'open') }
  
  validates :resource_type, presence: true
  validates :project_id, presence: true
  validates :offeror_id, presence: true
  validates :name, presence: true
  
  attr_accessible :project_id, :name, :text, :limit, :timezone, :from_raw, :to_raw, :resource_type, :candidatures_attributes
  
  before_validation :set_defaults
  
  def candidatures_left
    if limit
      limit - candidatures.accepted.count
    else
      '∞'
    end
  end
  
  def from_raw
    timezone && from ? from.in_time_zone(timezone).strftime('%Y-%m-%d %H:%M:%S') : ''
  end
  
  def from_raw=(value)
    if timezone && value.present?
      datetime = Time.zone.parse(value)
      args = [
        datetime.strftime('%Y').to_i, datetime.strftime('%m').to_i, datetime.strftime('%d').to_i,
        datetime.strftime('%H').to_i, datetime.strftime('%M').to_i, datetime.strftime('%S').to_i
      ]
      timezone_was = Time.zone
      Time.zone = timezone
      self.from = Time.zone.local *args
    end
  end
  
  def to_raw
    timezone && to ? to.in_time_zone(timezone).strftime('%Y-%m-%d %H:%M:%S') : ''
  end
  
  def to_raw=(value)
    if timezone && value.present?
      datetime = Time.zone.parse(value)
      args = [
        datetime.strftime('%Y').to_i, datetime.strftime('%m').to_i, datetime.strftime('%d').to_i,
        datetime.strftime('%H').to_i, datetime.strftime('%M').to_i, datetime.strftime('%S').to_i
      ]
      timezone_was = Time.zone
      Time.zone = timezone
      self.to = Time.zone.local *args
    end
  end
  
  def ended?
    if from.present? && Time.now < from
      false
    elsif from.blank? && to.present? && Time.now < to
      false
    elsif from.blank? && to.present?
      true
    elsif from.blank?
      false
    else
      true
    end
  end
  
  def calculate_accepted_candidatures_amount
    candidatures.accepted.count
  end
  
  def create_project_user?
    true
  end
  
  protected
  
  def set_defaults
    if project
      self.offeror_id = project.user_id
      self.author_id = project.user_id unless self.author_id.present?
    end
  end
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  include Applicat::Mvc::Controller::Resource
  
  before_filter :find_vacancy
  
  load_and_authorize_resource
  
  before_filter :find_project, only: [:index, :new, :edit]
  
  respond_to :html, :js, :json
  
  def index
    @vacancies = @project ? @project.vacancies : Vacancy.where(type: nil).all
  end
  
  def show
    @comments = @vacancy.comments
  end
  
  def new
    @vacancy = Vacancy.new
    
    @vacancy.project = @project if @project
  end
  
  def create
    @vacancy = Vacancy.new(params[:vacancy])
    @vacancy.resource_type = 'User'
    
    if @vacancy.project.user_id == current_user.id
      @vacancy.do_open
    else
      @vacancy.author_id = current_user.id 
      @vacancy.recommend
    end
    
    if @vacancy.save
      redirect_to @vacancy, notice: t('general.form.successfully_created')
    else
      render :new
    end
  end
  
  def edit
    @vacancy = Vacancy.find(params[:id])
  end
  
  def update
    @vacancy = Vacancy.find(params[:id])
    
    if @vacancy.update_attributes(params[:vacancy])
      redirect_to @vacancy, notice: t('general.form.successfully_updated')
    else
      render :edit
    end
  end

  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy
    redirect_to vacancies_url, notice: t('general.form.destroyed')
  end
  
  def resource
    @vacancy
  end
  
  transition_actions Vacancy::EVENTS
  
  protected
  
  def before_my_state
    # e.g. set attributes of resource
  end
  
  private
  
  def find_vacancy
    return unless params[:id].present?
    
    @vacancy = Vacancy
    @vacancy = @vacancy.includes(:project, :candidatures, :comments) if action_name == 'show'
    @vacancy = @vacancy.find(params[:id])
  end
  
  def find_project
    @project = params[:project_id].present? ? Project.friendly.find(params[:project_id]) : nil
  end
end

app/controllers/workflow/vacancies_controller.rb
class Workflow::VacanciesController < ApplicationController
  def open
    @vacancies = Vacancy.where(state: 'open')
  end
  
  def recommended
    @vacancies = Vacancy.where(state: 'recommended') 
  end
  
  def denied
    @vacancies = Vacancy.where(state: 'denied')
  end
  
  def closed
    @vacancies = Vacancy.where(state: 'closed')
  end
end

app/views/vacancies/_form.html.erb
<%= simple_form_for(@vacancy, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
  <%= render partial: 'shared/form/error_messages', locals: { resource: @vacancy } %>
  
  <%= @vacancy.project ? f.hidden_field(:project_id) : f.association(:project) %> 
  
  <%= f.input :name %>
  <%= f.input :text, input_html: {style: 'width: 500px; height:300px;'} %>
  <%= f.input :limit %> 
  
  <div class="form-group string optional vacancy_timezone">
    <label class="string optional control-label col-sm-3 control-label" for="vacancy_timezone">
      <%= t('attributes.timezone') %>
    </label>
    <div class="col-sm-9">
      <%= time_zone_select @vacancy, :timezone, nil, {}, id: 'vacancy_timezone', name: 'vacancy[timezone]', class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-group string optional vacancy_from">
    <label class="string optional control-label col-sm-3 control-label" for="vacancy_from">
      <%= t('activerecord.attributes.vacancy.from') %>
    </label>
    <div class="col-sm-9">
      <div class="datetime_picker" class="input-append date">
        <%= text_field_tag :from_raw, @vacancy.from_raw, name: 'vacancy[from_raw]', 'data-format' => 'yyyy-MM-dd hh:mm:ss' %>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar">
          </i>
        </span>
      </div>
    </div>
  </div>
  
  <div class="form-group string optional vacancy_to">
    <label class="string optional control-label col-sm-3 control-label" for="vacancy_to">
      <%= t('activerecord.attributes.vacancy.to') %>
    </label>
    <div class="col-sm-9">
      <div class="datetime_picker" class="input-append date">
        <%= text_field_tag :to_raw, @vacancy.to_raw, name: 'vacancy[to_raw]', 'data-format' => 'yyyy-MM-dd hh:mm:ss' %>
        <span class="add-on">
          <i data-time-icon="icon-time" data-date-icon="icon-calendar">
          </i>
        </span>
      </div>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

<% content_for :document_ready do %>
  $('#vacancy_timezone').val('<%= @vacancy.timezone %>')
<% end %>

app/views/vacancies/edit.html.erb
<h3><%= t('vacancies.edit.title') %></h3>

<%= render 'form' %>

app/views/vacancies/index.html.erb
<%= form_tag update_multiple_candidatures_path, method: :post do %>
  <%= render partial: "shared/collection/#{@project ? 'list' : 'table'}", locals: { 
    type: 'vacancies', collection: @vacancies, columns: ['name', 'project_id'], content_column: 'text'
  } %>
<% end %>

<%= link_to t('vacancies.new.title'), new_project_vacancy_path(@project) if @project %>

app/views/vacancies/new.html.erb
<h3><%= t('vacancies.new.title') %></h3>

<%= render 'form' %>

app/views/vacancies/show.html.erb
<h3>
  <a id="top" name="top"></a>
  <%= @vacancy.name %>
</h3>

<dl class="dl-horizontal">
  <%= show_associations :project %>
  <%= show_attribute :limit, value: "#{@vacancy.calculate_accepted_candidatures_amount} / #{@vacancy.limit ? @vacancy.limit : '∞'}" %>
  <%= show_attribute :state %>
  <%= show_actions %>
</dl>

<%= markdown @vacancy.text %>

<%= render 'shared/comments', comment: @vacancy.comments.new %>